2025-06-05 19:14:13,152 - root - INFO - Logging to E:\EmotionAnalysis\Emotions-Analysis\outputs\logs\20250605_191413_training.log
2025-06-05 19:14:13,152 - root - INFO - Starting training pipeline...
2025-06-05 19:14:13,152 - root - INFO - Using device: cuda
2025-06-05 19:14:14,010 - root - INFO - Loaded tokenizer with vocab size: 30522
2025-06-05 19:14:14,010 - root - INFO - Loading data from raw files...
2025-06-05 19:14:14,010 - root - INFO - Loading raw data...
2025-06-05 19:14:14,397 - root - INFO - Preprocessing data ...
2025-06-05 19:14:16,071 - root - INFO - Data sizes - Train: 5548, Val: 686, Test: 693
2025-06-05 19:14:16,071 - root - INFO - Data loaded - Train: 5548, Val: 686, Test: 693
2025-06-05 19:14:16,078 - root - INFO - Train set unique emotions: [6 5 0 2 3 1 4]
2025-06-05 19:14:16,078 - root - INFO - Val set unique emotions: [6 0 1 2 4 5 3]
2025-06-05 19:14:16,078 - root - INFO - Creating datasets...
2025-06-05 19:14:16,078 - root - INFO - Setting vocab size to 30522
2025-06-05 19:14:16,080 - root - INFO - Creating dataloaders...
2025-06-05 19:14:16,080 - root - INFO - Initializing trainer...
2025-06-05 19:14:16,315 - root - INFO - Starting training...
2025-06-05 19:53:32,393 - root - INFO - Training completed. Best validation loss: 0.9450
2025-06-05 19:53:32,469 - root - INFO - Final model saved to E:\EmotionAnalysis\Emotions-Analysis\outputs\models\final_model.pt
2025-06-05 19:53:32,469 - root - INFO - Evaluating on validation set...
2025-06-05 19:53:59,962 - root - INFO - Validation evaluation report saved to E:\EmotionAnalysis\Emotions-Analysis\outputs\validation_evaluation_report.txt
2025-06-05 19:53:59,962 - root - INFO - 
Validation Set Results:
2025-06-05 19:53:59,962 - root - INFO - Accuracy: 0.4539
2025-06-05 19:53:59,962 - root - INFO - Precision: 0.4643
2025-06-05 19:53:59,962 - root - INFO - Recall: 0.4539
2025-06-05 19:53:59,962 - root - INFO - F1: 0.4439
2025-06-05 19:53:59,962 - root - INFO - Confusion_matrix_path: E:\EmotionAnalysis\Emotions-Analysis\outputs\figures\confusion_matrix_20250605_195359.png
2025-06-05 19:53:59,962 - root - INFO - Loading best model from E:\EmotionAnalysis\Emotions-Analysis\outputs\models\best_model.pt
2025-06-05 19:54:00,036 - root - ERROR - An error occurred: cannot access local variable 'test_metrics' where it is not associated with a value
Traceback (most recent call last):
  File "E:\EmotionAnalysis\Emotions-Analysis\main.py", line 160, in main
    generate_evaluation_report(test_metrics, report_test_path)
                               ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'test_metrics' where it is not associated with a value
